<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260718000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the PartnerOps PostgreSQL domain schema and immutable audit log';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql('CREATE EXTENSION IF NOT EXISTS btree_gist');

        $this->addSql(<<<'SQL'
            CREATE TABLE client (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                name VARCHAR(120) NOT NULL,
                slug VARCHAR(80) NOT NULL,
                is_archived BOOLEAN DEFAULT FALSE NOT NULL,
                archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT chk_client_name CHECK (char_length(btrim(name)) BETWEEN 2 AND 120),
                CONSTRAINT chk_client_slug CHECK (slug = lower(btrim(slug)) AND slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
                CONSTRAINT chk_client_archive_state CHECK ((is_archived AND archived_at IS NOT NULL) OR (NOT is_archived AND archived_at IS NULL))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7440455B5B48B91 ON client (public_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_client_slug_lower ON client (lower(slug))');

        $this->addSql(<<<'SQL'
            CREATE TABLE app_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                email VARCHAR(180) NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                display_name VARCHAR(100) NOT NULL,
                role VARCHAR(20) NOT NULL,
                client_id BIGINT DEFAULT NULL,
                is_active BOOLEAN DEFAULT TRUE NOT NULL,
                deactivated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_88BDF3E919EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT,
                CONSTRAINT chk_user_email CHECK (email = lower(btrim(email)) AND char_length(email) BETWEEN 3 AND 180),
                CONSTRAINT chk_user_name CHECK (char_length(btrim(display_name)) BETWEEN 2 AND 100),
                CONSTRAINT chk_user_role CHECK (role IN ('admin', 'agent', 'client')),
                CONSTRAINT chk_user_client_role CHECK ((role = 'client' AND client_id IS NOT NULL) OR (role IN ('admin', 'agent') AND client_id IS NULL)),
                CONSTRAINT chk_user_active_state CHECK ((is_active AND deactivated_at IS NULL) OR (NOT is_active AND deactivated_at IS NOT NULL))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9B5B48B91 ON app_user (public_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email_lower ON app_user (lower(email))');
        $this->addSql('CREATE INDEX IDX_88BDF3E919EB6921 ON app_user (client_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE service_request (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                client_id BIGINT NOT NULL,
                requester_id BIGINT DEFAULT NULL,
                created_by_credential_id BIGINT DEFAULT NULL,
                assignee_id BIGINT DEFAULT NULL,
                title VARCHAR(160) NOT NULL,
                description TEXT NOT NULL,
                priority VARCHAR(20) DEFAULT 'normal' NOT NULL,
                status VARCHAR(24) DEFAULT 'new' NOT NULL,
                due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                version INT DEFAULT 1 NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_F413DD0319EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT,
                CONSTRAINT FK_F413DD03ED442CF4 FOREIGN KEY (requester_id) REFERENCES app_user (id) ON DELETE RESTRICT,
                CONSTRAINT FK_F413DD0359EC7D60 FOREIGN KEY (assignee_id) REFERENCES app_user (id) ON DELETE RESTRICT,
                CONSTRAINT chk_request_title CHECK (char_length(btrim(title)) BETWEEN 3 AND 160),
                CONSTRAINT chk_request_description CHECK (char_length(btrim(description)) BETWEEN 10 AND 10000),
                CONSTRAINT chk_request_priority CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
                CONSTRAINT chk_request_status CHECK (status IN ('new', 'in_progress', 'waiting_client', 'resolved', 'closed')),
                CONSTRAINT chk_request_version CHECK (version >= 1),
                CONSTRAINT chk_request_origin CHECK ((requester_id IS NOT NULL) <> (created_by_credential_id IS NOT NULL)),
                CONSTRAINT chk_request_resolved_at CHECK (status <> 'resolved' OR resolved_at IS NOT NULL),
                CONSTRAINT chk_request_closed_at CHECK (status <> 'closed' OR closed_at IS NOT NULL)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F413DD03B5B48B91 ON service_request (public_id)');
        $this->addSql('CREATE INDEX IDX_F413DD0319EB6921 ON service_request (client_id)');
        $this->addSql('CREATE INDEX IDX_F413DD03ED442CF4 ON service_request (requester_id)');
        $this->addSql('CREATE INDEX idx_request_created_by_credential ON service_request (created_by_credential_id)');
        $this->addSql('CREATE INDEX IDX_F413DD0359EC7D60 ON service_request (assignee_id)');
        $this->addSql('CREATE INDEX idx_request_client_status_created ON service_request (client_id, status, created_at DESC)');
        $this->addSql('CREATE INDEX idx_request_assignee_status_created ON service_request (assignee_id, status, created_at DESC)');
        $this->addSql("CREATE INDEX idx_request_open_due ON service_request (due_at, priority) WHERE status NOT IN ('closed', 'resolved')");
        $this->addSql('CREATE INDEX idx_request_team_queue ON service_request (status, priority, created_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE comment (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                service_request_id BIGINT NOT NULL,
                author_id BIGINT NOT NULL,
                body TEXT NOT NULL,
                is_internal BOOLEAN DEFAULT FALSE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_9474526CD42F8111 FOREIGN KEY (service_request_id) REFERENCES service_request (id) ON DELETE RESTRICT,
                CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE RESTRICT,
                CONSTRAINT chk_comment_body CHECK (char_length(btrim(body)) BETWEEN 1 AND 5000)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9474526CB5B48B91 ON comment (public_id)');
        $this->addSql('CREATE INDEX IDX_9474526CD42F8111 ON comment (service_request_id)');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)');
        $this->addSql('CREATE INDEX idx_comment_request_created ON comment (service_request_id, created_at ASC)');

        $this->addSql(<<<'SQL'
            CREATE TABLE allowance_period (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                client_id BIGINT NOT NULL,
                starts_on DATE NOT NULL,
                ends_on DATE NOT NULL,
                included_minutes INT NOT NULL,
                created_by_id BIGINT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_A1568AE619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT,
                CONSTRAINT FK_A1568AE6B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE RESTRICT,
                CONSTRAINT chk_allowance_dates CHECK (ends_on >= starts_on),
                CONSTRAINT chk_allowance_minutes CHECK (included_minutes BETWEEN 1 AND 1000000),
                CONSTRAINT excl_allowance_period_overlap EXCLUDE USING gist (client_id WITH =, daterange(starts_on, ends_on, '[]') WITH &&)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1568AE6B5B48B91 ON allowance_period (public_id)');
        $this->addSql('CREATE INDEX IDX_A1568AE619EB6921 ON allowance_period (client_id)');
        $this->addSql('CREATE INDEX IDX_A1568AE6B03A8386 ON allowance_period (created_by_id)');
        $this->addSql('CREATE INDEX idx_allowance_client_dates ON allowance_period (client_id, starts_on, ends_on)');

        $this->addSql(<<<'SQL'
            CREATE TABLE time_entry (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                service_request_id BIGINT NOT NULL,
                allowance_period_id BIGINT NOT NULL,
                author_id BIGINT NOT NULL,
                minutes INT NOT NULL,
                description VARCHAR(500) NOT NULL,
                is_client_visible BOOLEAN DEFAULT TRUE NOT NULL,
                approval_status VARCHAR(20) DEFAULT 'approved' NOT NULL,
                work_date DATE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_6E537C0CD42F8111 FOREIGN KEY (service_request_id) REFERENCES service_request (id) ON DELETE RESTRICT,
                CONSTRAINT FK_6E537C0C884AED83 FOREIGN KEY (allowance_period_id) REFERENCES allowance_period (id) ON DELETE RESTRICT,
                CONSTRAINT FK_6E537C0CF675F31B FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE RESTRICT,
                CONSTRAINT chk_time_minutes CHECK (minutes BETWEEN 1 AND 1440),
                CONSTRAINT chk_time_description CHECK (char_length(btrim(description)) BETWEEN 3 AND 500),
                CONSTRAINT chk_time_approval CHECK (approval_status IN ('approved'))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6E537C0CB5B48B91 ON time_entry (public_id)');
        $this->addSql('CREATE INDEX IDX_6E537C0CD42F8111 ON time_entry (service_request_id)');
        $this->addSql('CREATE INDEX IDX_6E537C0C884AED83 ON time_entry (allowance_period_id)');
        $this->addSql('CREATE INDEX IDX_6E537C0CF675F31B ON time_entry (author_id)');
        $this->addSql('CREATE INDEX idx_time_allowance_approval ON time_entry (allowance_period_id, approval_status)');
        $this->addSql('CREATE INDEX idx_time_request_created ON time_entry (service_request_id, created_at DESC)');

        $this->addSql(<<<'SQL'
            CREATE TABLE audit_event (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                client_id BIGINT DEFAULT NULL,
                actor_id BIGINT DEFAULT NULL,
                actor_type VARCHAR(24) NOT NULL,
                "action" VARCHAR(80) NOT NULL,
                subject_type VARCHAR(60) NOT NULL,
                subject_public_id CHAR(26) DEFAULT NULL,
                metadata JSONB NOT NULL,
                trace_id VARCHAR(64) NOT NULL,
                occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_3CE56E5019EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT,
                CONSTRAINT FK_3CE56E5010DAF24A FOREIGN KEY (actor_id) REFERENCES app_user (id) ON DELETE RESTRICT,
                CONSTRAINT chk_audit_actor_type CHECK (actor_type IN ('user', 'api_credential', 'system', 'anonymous')),
                CONSTRAINT chk_audit_actor CHECK ((actor_type = 'user' AND actor_id IS NOT NULL) OR (actor_type <> 'user' AND actor_id IS NULL)),
                CONSTRAINT chk_audit_action CHECK ("action" ~ '^[a-z][a-z0-9_.]{1,79}$'),
                CONSTRAINT chk_audit_subject CHECK (subject_type ~ '^[a-z][a-z0-9_]{1,59}$'),
                CONSTRAINT chk_audit_metadata CHECK (jsonb_typeof(metadata) = 'object'),
                CONSTRAINT chk_audit_trace CHECK (char_length(trace_id) BETWEEN 1 AND 64)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3CE56E50B5B48B91 ON audit_event (public_id)');
        $this->addSql('CREATE INDEX IDX_3CE56E5019EB6921 ON audit_event (client_id)');
        $this->addSql('CREATE INDEX IDX_3CE56E5010DAF24A ON audit_event (actor_id)');
        $this->addSql('CREATE INDEX idx_audit_client_occurred ON audit_event (client_id, occurred_at DESC)');
        $this->addSql('CREATE INDEX idx_audit_action_occurred ON audit_event ("action", occurred_at DESC)');
        $this->addSql('CREATE INDEX idx_audit_subject_occurred ON audit_event (subject_type, subject_public_id, occurred_at)');
        $this->addSql(<<<'SQL'
            CREATE FUNCTION partnerops_reject_audit_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'audit_event is append-only' USING ERRCODE = '55000';
            END;
            $$
            SQL);
        $this->addSql('CREATE TRIGGER audit_event_immutable BEFORE UPDATE OR DELETE ON audit_event FOR EACH ROW EXECUTE FUNCTION partnerops_reject_audit_mutation()');

        $this->addSql(<<<'SQL'
            CREATE TABLE api_credential (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id CHAR(26) NOT NULL,
                client_id BIGINT NOT NULL,
                name VARCHAR(100) NOT NULL,
                selector VARCHAR(20) NOT NULL,
                token_prefix VARCHAR(24) NOT NULL,
                secret_hash CHAR(64) NOT NULL,
                last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_by_id BIGINT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_C2D5615A19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT,
                CONSTRAINT FK_C2D5615AB03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE RESTRICT,
                CONSTRAINT chk_credential_name CHECK (char_length(btrim(name)) BETWEEN 2 AND 100),
                CONSTRAINT chk_credential_selector CHECK (selector ~ '^[A-Za-z0-9_-]{4,20}$'),
                CONSTRAINT chk_credential_prefix CHECK (char_length(token_prefix) BETWEEN 1 AND 24),
                CONSTRAINT chk_credential_hash CHECK (secret_hash ~ '^[a-f0-9]{64}$')
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C2D5615AB5B48B91 ON api_credential (public_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C2D5615A9692E25D ON api_credential (selector)');
        $this->addSql('CREATE INDEX IDX_C2D5615A19EB6921 ON api_credential (client_id)');
        $this->addSql('CREATE INDEX IDX_C2D5615AB03A8386 ON api_credential (created_by_id)');
        $this->addSql('CREATE INDEX idx_credential_client_active ON api_credential (client_id, revoked_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_credential_active_name ON api_credential (client_id, lower(name)) WHERE revoked_at IS NULL');
        $this->addSql('ALTER TABLE service_request ADD CONSTRAINT fk_request_created_by_credential FOREIGN KEY (created_by_credential_id) REFERENCES api_credential (id) ON DELETE RESTRICT');

        $this->addSql(<<<'SQL'
            CREATE TABLE idempotency_record (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                api_credential_id BIGINT NOT NULL,
                idempotency_key VARCHAR(128) NOT NULL,
                request_fingerprint CHAR(64) NOT NULL,
                service_request_id BIGINT NOT NULL,
                response_status SMALLINT NOT NULL,
                response_body JSONB NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT FK_A68190E58D351229 FOREIGN KEY (api_credential_id) REFERENCES api_credential (id) ON DELETE RESTRICT,
                CONSTRAINT FK_A68190E5D42F8111 FOREIGN KEY (service_request_id) REFERENCES service_request (id) ON DELETE RESTRICT,
                CONSTRAINT chk_idempotency_key CHECK (idempotency_key ~ '^[!-~]+$'),
                CONSTRAINT chk_idempotency_fingerprint CHECK (request_fingerprint ~ '^[a-f0-9]{64}$'),
                CONSTRAINT chk_idempotency_status CHECK (response_status = 201),
                CONSTRAINT chk_idempotency_response CHECK (jsonb_typeof(response_body) = 'object'),
                CONSTRAINT chk_idempotency_expiry CHECK (expires_at > created_at)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_A68190E58D351229 ON idempotency_record (api_credential_id)');
        $this->addSql('CREATE INDEX IDX_A68190E5D42F8111 ON idempotency_record (service_request_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_idempotency_credential_key ON idempotency_record (api_credential_id, idempotency_key)');
        $this->addSql('CREATE INDEX idx_idempotency_expires ON idempotency_record (expires_at)');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql('DROP TABLE idempotency_record');
        $this->addSql('DROP TRIGGER audit_event_immutable ON audit_event');
        $this->addSql('DROP TABLE audit_event');
        $this->addSql('DROP FUNCTION partnerops_reject_audit_mutation()');
        $this->addSql('DROP TABLE time_entry');
        $this->addSql('DROP TABLE allowance_period');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE service_request');
        $this->addSql('DROP TABLE api_credential');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE client');
    }
}
