# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\DataFixtures\:
        resource: '../src/DataFixtures/'

    Doctrine\Bundle\DoctrineBundle\Middleware\BacktraceDebugDataHolder:
        alias: doctrine.debug_data_holder
        public: true
